[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/808gps/*"
  to = "/.netlify/functions/cam/808gps/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/js/*"
  to = "/.netlify/functions/cam/js/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
